[build]
  base = "UI/starkflux-ui"
  command = "npm run build"
  publish = "dist"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Enable CORS headers for contract interaction
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 